"""Add content field to ResumeVersion

Revision ID: 2b744a9cab5c
Revises: 78541af180f8
Create Date: 2026-05-07 10:45:58.335254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b744a9cab5c'
down_revision = '78541af180f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
