"""Add QuickLink model

Revision ID: 78541af180f8
Revises: b5a4ad9aa1ba
Create Date: 2026-05-07 10:04:42.183663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78541af180f8'
down_revision = 'b5a4ad9aa1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quick_links')
    # ### end Alembic commands ###
