"""add is_admin last_active_at ai_events

Revision ID: f517bde438f2
Revises: 2b744a9cab5c
Create Date: 2026-06-05 18:22:38.679990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f517bde438f2'
down_revision = '2b744a9cab5c'
branch_labels = None
depends_on = None


def upgrade():
    from alembic import op as _op
    import sqlalchemy as _sa
    from sqlalchemy.engine.reflection import Inspector
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)

    if 'ai_events' not in inspector.get_table_names():
        op.create_table('ai_events',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('event_type', sa.String(length=50), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    existing_cols = [c['name'] for c in inspector.get_columns('users')]
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'is_admin' not in existing_cols:
            batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))
        if 'last_active_at' not in existing_cols:
            batch_op.add_column(sa.Column('last_active_at', sa.DateTime(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_active_at')
        batch_op.drop_column('is_admin')

    op.drop_table('ai_events')
    # ### end Alembic commands ###
